version: "2"
services:
  mongodb:
    image: mongo:3.4
    hostname: mongodb
    container_name: mongodb
    expose:
      - "27017"
    command: --smallfiles

  orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: orion
    links:
      - mongodb
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongodb

  mosquitto:
    image: ansi/mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
    ports:
      - "1883:1883"

  idas:
    image: fiware/iotagent-ul:develop
    hostname: idas
    container_name: idas
    volumes:
      - ./config-blank.js:/opt/iotaul/config-blank.js
    links:
      - mongodb:mongo
      - orion
      - mosquitto
    expose:
      - "7896"
      - "4041"
    ports:
      - "7896:7896"
      - "4041:4041"

  perseo:
    image: telefonicaiot/perseo-fe
    hostname: perseo
    container_name: perseo
    links:
      - mongodb-perseo
      - perseo-core
      - orion
    expose:
      - "9090"
    ports:
      - "9090:9090"
    environment:
      - PERSEO_MONGO_HOST=mongodb-perseo
      - PERSEO_CORE_URL=http://perseo-core:8080
      - PERSEO_ORION_URL=http://orion:1026/v1/updateContext
#      - PERSEO_SMTP_HOST=
#      - PERSEO_SMTP_PORT=
#      - PERSEO_SMTP_SECURE=
#      - PERSEO_SMTP_AUTH_USER=
#      - PERSEO_SMTP_AUTH_PASS=

  perseo-core:
    image: telefonicaiot/perseo-core
    hostname: perseo-core
    container_name: perseo-core
    volumes:
      - ./perseo-core.properties:/etc/perseo-core.properties
    expose:
      - "8080"
    ports:
      - "8080:8080"

  mongodb-perseo:
    image: mongo:3.4
    hostname: mongodb-perseo
    container_name: mongodb-perseo
    expose:
      - "27017"
    command: --smallfiles

  # sth-comet:
  #   image: telefonicaiot/fiware-sth-comet
  #   # image: fiware/sth-comet
  #   hostname: sth-comet
  #   container_name: sth-comet
  #   # volumes:
  #   #   - ./config/sth/config.js:/opt/sth/config.js
  #   links:
  #     - mongodb-comet
  #   ports:
  #     - "8666:8666"
  #   environment:
  #     # - DEFAULT_SERVICE="OpenIoT"
  #     # - DEFAULT_SERVICE_PATH="/"
  #     - STH_HOST=0.0.0.0
  #     - DB_URI=mongodb-comet:27017
  #
  # mongodb-comet:
  #   image: mongo:3.4
  #   hostname: mongodb-comet
  #   container_name: mongodb-comet
  #
  # authzforce:
  #   image: fiware/authzforce-ce-server:release-5.4.1
  #   hostname: authzforce
  #   container_name: authzforce
  #   ports:
  #     - "8080:8080"
  #   expose:
  #     - "8080"
  #
  # keyrock:
  #   image: fiware/idm
  #   hostname: keyrock
  #   container_name: keyrock
  #   links:
  #     - authzforce
  #   expose:
  #     - "5000"
  #     - "8000"
  #   ports:
  #     - "5000:5000"
  #     - "8000:8000"
  #
  # mysql:
  #   image: mysql:5.5
  #   hostname: mysql
  #   container_name: mysql
  #   expose:
  #     - "3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=mysql
  #
  # cygnus:
  #   image: fiware/cygnus-ngsi:develop
  #   hostname: cygnus
  #   container_name: cygnus
  #   volumes:
  #     - ./config/cygnus/agent.conf:/opt/apache-flume/conf/agent.conf
  #   links:
  #     - orion
  #     # - mysql:mysql
  #   expose:
  #     - "5050"
  #   # environment:
  #   #   - CYGNUS_MYSQL_HOST=mysql
  #   #   - CYGNUS_MYSQL_USER=root
  #   #   - CYGNUS_MYSQL_PASS=mysql
