version: "2"
services:
  mongodb:
    image: mongo:3.4.2
    hostname: mongodb
    container_name: mongodb
    expose:
      - "27017"
    ports:
      - "27019:27017"
    command: mongod --smallfiles

  orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: orion
    links:
      - mongodb
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongodb

  mosquitto:
    image: ansi/mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
    ports:
      - "1883:1883"

  idas:
    image: fiware/iotagent-ul:develop
    hostname: idas
    container_name: idas
    volumes:
      - ./config/idas/config-blank.js:/opt/iotaul/config-blank.js
    links:
      - mongodb:mongo
      - orion
      - mosquitto
    expose:
      - "7896"
      - "4041"
    ports:
      - "7896:7896"
      - "4041:4041"

  perseo:
    image: telefonicaiot/perseo-fe
    hostname: perseo
    container_name: perseo
    links:
      - mongodb-perseo
      - perseo-core
      - orion
    expose:
      - "9090"
    ports:
      - "9090:9090"
    environment:
      - PERSEO_MONGO_HOST=mongodb-perseo
      - PERSEO_CORE_URL=http://perseo-core:8080
      - PERSEO_ORION_URL=http://orion:1026/v1/updateContext
      # - PERSEO_SMTP_HOST=
      # - PERSEO_SMTP_PORT=
      # - PERSEO_SMTP_SECURE=
      # - PERSEO_SMTP_AUTH_USER=
      # - PERSEO_SMTP_AUTH_PASS=

  perseo-core:
    image: telefonicaiot/perseo-core
    hostname: perseo-core
    container_name: perseo-core
    volumes:
      - ./config/perseo/perseo-core.properties:/etc/perseo-core.properties
    expose:
      - "8080"
    ports:
      - "8080:8080"

  mongodb-perseo:
    image: mongo:3.4.2
    hostname: mongodb-perseo
    container_name: mongodb-perseo
    expose:
      - "27017"
    command: --smallfiles

  sth-comet:
    image: telefonicaiot/fiware-sth-comet
    hostname: sth-comet
    container_name: sth-comet
    volumes:
      - ./config/sth/config.js:/opt/sth/config.js
    links:
      - mongodb-cygnus
    expose:
      - "8666"
    ports:
      - "8666:8666"

  mongodb-cygnus:
    image: mongo:3.4.2
    hostname: mongodb-cygnus
    container_name: mongodb-cygnus
    expose:
      - "27017"
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  mysql-cygnus:
    image: mysql
    hostname: mysql-cygnus
    container_name: mysql-cygnus
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql

  cygnus:
    image: fiware/cygnus-ngsi:1.7.1
    hostname: cygnus
    container_name: cygnus
    volumes:
      - ./config/cygnus/agent.conf:/opt/apache-flume/conf/agent.conf
      - ./config/cygnus/lib/elasticsearch-0.90.13.jar:/opt/apache-flume/lib/elasticsearch-0.90.13.jar
      - ./config/cygnus/lib/lucene-core-4.6.1.jar:/opt/apache-flume/lib/lucene-core-4.6.1.jar
    links:
      - orion
      - mysql-cygnus:mysql-cygnus
      - elasticsearch
    expose:
      - "5050"
    ports:
      - "5050:5050"
    environment:
      - CYGNUS_MYSQL_HOST=mysql-cygnus
      - CYGNUS_MYSQL_PORT=3306
      - CYGNUS_MYSQL_USER=root
      - CYGNUS_MYSQL_PASS=mysql
      - CYGNUS_MONGO_HOSTS=mongodb-cygnus:27017
      - CYGNUS_MONGO_USER=
      - CYGNUS_MONGO_PASS=
      - CYGNUS_LOG_LEVEL=DEBUG

  elasticsearch:
    image: barnybug/elasticsearch:0.90.13
    hostname: elasticsearch
    container_name: elasticsearch
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: andrewh/kibana3
    hostname: kibana
    container_name: kibana
    links:
      - elasticsearch
    expose:
      - "8080"
    ports:
      - "8081:8080"
    environment:
      - ES_PROTO=http
      - ES_HOST=192.168.99.100
      - ES_PORT=9200

  # authzforce:
  #   image: fiware/authzforce-ce-server:release-5.4.1
  #   hostname: authzforce
  #   container_name: authzforce
  #   ports:
  #     - "8080:8080"
  #   expose:
  #     - "8080"
  #
  # keyrock:
  #   image: fiware/idm
  #   hostname: keyrock
  #   container_name: keyrock
  #   links:
  #     - authzforce
  #   expose:
  #     - "5000"
  #     - "8000"
  #   ports:
  #     - "5000:5000"
  #     - "8000:8000"
