version: "2"
services:
  cygnus:
    image: fiware/cygnus-ngsi:1.7.1
    hostname: cygnus
    container_name: cygnus
    volumes:
      - ./config/cygnus/agent.conf:/opt/apache-flume/conf/agent.conf
    links:
      - mysql-cygnus:mysql-cygnus
    expose:
      - "5050"
    ports:
      - "5050:5050"
    environment:
      - CYGNUS_MYSQL_HOST=mysql-cygnus
      - CYGNUS_MYSQL_PORT=3306
      - CYGNUS_MYSQL_USER=root
      - CYGNUS_MYSQL_PASS=mysql
      - CYGNUS_MONGO_HOSTS=mongodb-cygnus:27017
      - CYGNUS_MONGO_USER=
      - CYGNUS_MONGO_PASS=
      - CYGNUS_LOG_LEVEL=INFO

  mysql-cygnus:
    image: mysql
    hostname: mysql-cygnus
    container_name: mysql-cygnus
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - mysql-volume:/var/lib/mysql

  mongodb-cygnus:
    image: mongo:3.4.2
    hostname: mongodb-cygnus
    container_name: mongodb-cygnus
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongodb-volume:/data
    command: mongod --smallfiles

  sth-comet:
    image: telefonicaiot/fiware-sth-comet
    hostname: sth-comet
    container_name: sth-comet
    volumes:
      - ./config/sth/config.js:/opt/sth/config.js
    links:
      - mongodb-cygnus
    expose:
      - "8666"
    ports:
      - "8666:8666"

volumes:
  mysql-volume:
  mongodb-volume:
